---

- name: set up prereqs
  apt:
    state: latest
    name:
      - nfs-common
      - htop

- name: create mount point
  file:
    path: /mnt/home
    state: directory
    mode: 0777
    owner: ubuntu
    group: ubuntu

- name: mount nfs share (homedirs)
  mount:
    name: /mnt/home
    src: "{{ hostvars.localhost.jump_hosts.instances[0].private_ip_address }}:/"
    fstype: nfs
    state: mounted

- name: update fstab
  lineinfile:
    dest: /etc/fstab
    insertafter: EOF
    line: "{{ hostvars.localhost.jump_hosts.instances[0].private_ip_address }}:/ /mnt/home nfs auto 0 0"

- name: create user accounts
  user:
    name: "{{ item.name }}"
    password: "{{ item.hash }}"
    group: "{{ item.group }}"
    uid: "{{ item.uid }}"
    shell: /usr/bin/zsh
    createhome: False
    home: "/mnt/home/{{ item.name }}"
  with_items: "{{ users }}"

- name: configure ssh
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes

- name: restart ssh
  service:
    name: ssh
    state: restarted
